### PR TITLE
refactor: Minor fixes

### LINKED ISSUE #310: 'layer4.matchers.ip': module not registered
README example failed with error "'layer4.matchers.ip': module not registered "

```
{
    layer4 {
        0.0.0.0:1080 {
            @s5 {
                socks5
                ip 10.0.0.0/24
            }
            route @s5 {
                socks5 {
                    credentials bob qHoEtVpGRM
                }
            }
            @s4 socks4
            route @s4 {
                proxy 10.64.0.1:1080
            }
        }
    }
}
```

./caddy list-modules | grep layer4
caddy.listeners.layer4
layer4
layer4.handlers.echo
layer4.handlers.proxy
layer4.handlers.proxy_protocol
layer4.handlers.socks5
layer4.handlers.subroute
layer4.handlers.tee
layer4.handlers.throttle
layer4.handlers.tls
layer4.matchers.clock
layer4.matchers.dns
layer4.matchers.http
layer4.matchers.local_ip
layer4.matchers.not
layer4.matchers.openvpn
layer4.matchers.postgres
layer4.matchers.proxy_protocol
layer4.matchers.quic
layer4.matchers.rdp
layer4.matchers.regexp
layer4.matchers.remote_ip
layer4.matchers.remote_ip_list
layer4.matchers.socks4
layer4.matchers.socks5
layer4.matchers.ssh
layer4.matchers.tls
layer4.matchers.winbox
layer4.matchers.wireguard
layer4.matchers.xmpp
layer4.proxy.selection_policies.first
layer4.proxy.selection_policies.ip_hash
layer4.proxy.selection_policies.least_conn
layer4.proxy.selection_policies.random
layer4.proxy.selection_policies.random_choose
layer4.proxy.selection_policies.round_robin

### PR DESCRIPTION
**Pull request by vnxme**
This PR includes a number of minor code style fixes and, *inter alia*, closes #310.

### CODE REVIEW

**Comment by IceCodeNew** [comment]
LGTM. Though I would rather wait for a couple of days in case anyone would like to do/request amendments.

**Comment by vnxme** [comment]
@mohammed90, I've added lint.yml in #321.

File: layer4/routes_test.go [hunk 1]
```diff
@@ -20,7 +20,7 @@ import (
 type testIoMatcher struct {
 }
 
-func (testIoMatcher) CaddyModule() caddy.ModuleInfo {
+func (*testIoMatcher) CaddyModule() caddy.ModuleInfo {
```
Comment (mholt) [inline layer4/routes_test.go:23]: Why the change to pointers?

**Review by mholt — APPROVED** [review]
Thanks -- overall looks good, but I do question the need for pointer receivers?

File: layer4/routes_test.go (hunk 1 above)
Comment (vnxme) [reply layer4/routes_test.go:23]: Otherwise I have a warning in the IDE saying the use of both value and pointer receivers for the same type is discouraged. Anyway, pointers don't make any harm there.
