### PR TITLE
fix route matching behavior when more data is needed

### LINKED ISSUE #356: Bug: With caddy-security, UDP fail to do the default route
When using `caddy-security` + `caddy-l4` , the default route (without tag) will not functional.

# Here is to reproduce

Software download: 
`https://caddyserver.com/download?package=github.com%2Fmholt%2Fcaddy-l4&package=github.com%2Fgreenpau%2Fcaddy-security`

## Caddyfile:
```
{
    admin off
    auto_https off
    debug
    layer4 {
        udp/:10842 {
            @ovpnudp openvpn
            route @ovpnudp {
                proxy udp/127.0.0.1:11111
            }

            route {
                echo
            }
        }
    }
}
```

Then `nc -u 127.0.0.1 10842` , press some words+enter, and got no echo.

## `Caddy-l4` only, which is functional. Logs:
```
root@ubuntu1:~/test/caddy-l4# ./caddy_linux_amd64_custom run
2025/12/18 11:52:04.995 INFO    maxprocs: Leaving GOMAXPROCS=3: CPU quota undefined
2025/12/18 11:52:04.997 INFO    GOMEMLIMIT is updated   {"package": "github.com/KimMachineGun/automemlimit/memlimit", "GOMEMLIMIT": 18875820441, "previous": 9223372036854775807}
2025/12/18 11:52:04.997 INFO    using adjacent Caddyfile
2025/12/18 11:52:04.997 INFO    adapted config to JSON  {"adapter": "caddyfile"}
2025/12/18 11:52:04.997 WARN    Caddyfile input is not formatted; run 'caddy fmt --overwrite' to fix inconsistencies    {"adapter": "caddyfile", "file": "Caddyfile", "line": 7}
2025/12/18 11:52:04.998 WARN    admin   admin endpoint disabled
2025/12/18 11:52:04.998 DEBUG   layer4  listening       {"address": "udp/[::]:10842"}
2025/12/18 11:52:04.998 INFO    autosaved config (load with --resume flag)      {"file": "/root/.config/caddy/autosave.json"}
2025/12/18 11:52:04.998 INFO    serving initial configuration
2025/12/18 11:52:06.425 DEBUG   layer4  matching        {"remote": "127.0.0.1:60202", "error": "consumed all prefetched bytes", "matcher": "layer4.matchers.openvpn", "matched": false}
2025/12/18 11:52:06.426 DEBUG   layer4  prefetched      {"remote": "127.0.0.1:60202", "bytes": 4}
2025/12/18 11:52:06.426 DEBUG   layer4  matching        {"remote": "127.0.0.1:60202", "matcher": "layer4.matchers.openvpn", "matched": false}
2025/12/18 11:52:36.455 DEBUG   layer4  connection stats        {"remote": "127.0.0.1:60202", "read": 4, "written": 4, "duration": 30.029538773}    ## Noted: this line were generated after 30s
```

## `Caddy-l4` + `Caddy-security`, which is NOT functional. Logs:
```
root@ubuntu1:~/test/caddy-l4# ./caddy_linux_amd64_custom3 run
2025/12/18 11:54:15.984 INFO    maxprocs: Leaving GOMAXPROCS=3: CPU quota undefined
2025/12/18 11:54:15.985 INFO    GOMEMLIMIT is updated   {"package": "github.com/KimMachineGun/automemlimit/memlimit", "GOMEMLIMIT": 18875820441, "previous": 9223372036854775807}
2025/12/18 11:54:15.986 INFO    using adjacent Caddyfile
2025/12/18 11:54:15.987 INFO    adapted config to JSON  {"adapter": "caddyfile"}
2025/12/18 11:54:15.987 WARN    Caddyfile input is not formatted; run 'caddy fmt --overwrite' to fix inconsistencies    {"adapter": "caddyfile", "file": "Caddyfile", "line": 7}
2025/12/18 11:54:15.988 WARN    admin   admin endpoint disabled
2025/12/18 11:54:15.989 DEBUG   layer4  listening       {"address": "udp/[::]:10842"}
2025/12/18 11:54:15.989 INFO    autosaved config (load with --resume flag)      {"file": "/root/.config/caddy/autosave.json"}
2025/12/18 11:54:15.989 INFO    serving initial configuration
2025/12/18 11:54:17.965 DEBUG   layer4  matching        {"remote": "127.0.0.1:52636", "error": "consumed all prefetched bytes", "matcher": "layer4.matchers.openvpn", "matched": false}
2025/12/18 11:54:17.965 DEBUG   layer4  prefetched      {"remote": "127.0.0.1:52636", "bytes": 4}
2025/12/18 11:54:17.965 DEBUG   layer4  matching        {"remote": "127.0.0.1:52636", "matcher": "layer4.matchers.openvpn", "matched": false}
2025/12/18 11:54:17.965 DEBUG   layer4  connection stats        {"remote": "127.0.0.1:52636", "read": 4, "written": 0, "duration": 0.000113558}
```

### PR DESCRIPTION
**Pull request by WeidiDeng**
Current route matching is kind of buggy when a route that matches everything is chosen, the condition to check is wrong. Instead of checking if there is anything route before current one that needs more data, the comparison is with if any of the routes needs more.

Now the check is to see if any route before the current one needs more. Also updated the logic behind updating the last index where a route requires more data.

Fix #356

### CODE REVIEW

File: layer4/routes.go [hunk 1]
```diff
@@ -111,9 +111,12 @@ func (routes RouteList) Compile(logger *zap.Logger, matchingTimeout time.Duratio
 
 		var (
 			lastMatchedRouteIdx = -1
-			lastNeedsMoreIdx    = -1
-			routesStatus        = make(map[int]int)
-			matcherNeedMore     bool
+			// it actually records where a matcher may require more data, i.e. the one that really needs more,
+			// it actually records where a matcher may require more data, i.e. the one that really needs more,
```
Comment (mholt) [inline layer4/routes.go]:
```suggestion
```

Accidental duplicate line I think

**Review by mholt — CHANGES_REQUESTED** [review]
Thanks Weidi! Just a couple nits about comments.
