### PR TITLE
subroute: Add support for subrouting

### LINKED ISSUE #20: Nested matching and handling
It is a common case that the client sends the HTTP traffic in a TLS session and the proxy forwards it upstream in PROXY protocol. I want to match PROXY protocol and then match TLS session, if the match fails then we should fallback to next route. To the best of my knowledge, there is currently no way to achieve such effect. I propose we implement a special handler called `nested` to handle such case. 

Below is an example configuration. Assume that we have already implemented a matcher called `proxyprotocol` which matches all traffic in PROXY protocol and a handler called `proxyprotocol` which turns PROXY protocol traffic into normal TCP traffic. The below configuration instructs `caddly-l4` to first matches proxy protocol, then unwraps PROXY protocol traffice and handles the unwrapped traffic with the specified routes, which in turn try to match it with tls and then terminate tls, if that fails, match it with the http matcher.

If the entire nested matcher failed to match the connection, we should fallback to the next route. My configuration below makes `caddy-l4` accept both traffic in PROXY protocol and in normal TCP connection.
```
{
  "apps": {
    "layer4": {
      "servers": {
        "example": {
          "listen": ["0.0.0.0:5000"],
          "routes": [
            {
              "match": [
                {
                  "proxyprotocol": {}
                }
              ],
              "handle": [
                {
                  "handler": "proxyprotocol"
                },
                {
                  "handler": "nested",
                  "routes": [
                    {
                      "match": [
                        {
                          "tls": {}
                        }
                      ],
                      "handle": [
                        {
                          "handler": "tls"
                        },
                        {
                          "handler": "proxy",
                          "upstreams": [{ "dial": ["localhost:8080"] }]
                        }
                      ]
                    },
                    {
                      "match": [
                        {
                          "http": [{ "host": ["example.com"] }]
                        }
                      ],
                      "handle": [
                        {
                          "handler": "proxy",
                          "upstreams": [{ "dial": ["localhost:8080"] }]
                        }
                      ]
                    }
                  ]
                }
              ]
            },
            {
              "match": [
                {
                  "tls": {}
                }
              ],
              "handle": [
                {
                  "handler": "tls"
                },
                {
                  "handler": "proxy",
                  "upstreams": [{ "dial": ["localhost:8080"] }]
                }
              ]
            },
            {
              "match": [
                {
                  "http": [{ "host": ["example.com"] }]
                }
              ],
              "handle": [
                {
                  "handler": "proxy",
                  "upstreams": [{ "dial": ["localhost:8080"] }]
                }
              ]
            }
          ]
        }
      }
    }
  }
}
```

### PR DESCRIPTION
**Pull request by RussellLuo**
This closes #20.

With the following JSON config:

```json
{
	"apps": {
		"layer4": {
			"servers": {
				"srv0": {
					"listen": ["127.0.0.1:5000"],
					"routes": [
						{
							"match": [
								{
									"http": [
										{"host": ["example.com"]}
									]
								}
							],
							"handle": [
								{
									"handler": "subroute",
									"routes": [
										{
											"match": [
												{
													"http": [
														{"path": ["/1"]}
													]
												}
											],
											"handle": [
												{
													"handler": "proxy",
													"upstreams": [
														{"dial": ["localhost:5001"]}
													]
												}
											]
										},
										{
											"match": [
												{
													"http": [
														{"path": ["/2"]}
													]
												}
											],
											"handle": [
												{
													"handler": "proxy",
													"upstreams": [
														{"dial": ["localhost:5002"]}
													]
												}
											]
										}
									]
								}
							]
						}
					]
				}
			}
		},
		"http": {
			"servers": {
				"srv0": {
					"listen": [
						":5001"
					],
					"routes": [
						{
							"handle": [
								{
									"body": "This is 5001",
									"handler": "static_response"
								}
							]
						}
					]
				},
				"srv1": {
					"listen": [
						":5002"
					],
					"routes": [
						{
							"handle": [
								{
									"body": "This is 5002",
									"handler": "static_response"
								}
							]
						}
					]
				}
			}
		}
	}
}
```

We can get the results as below:

```bash
$ curl -H 'Host: example.com' http://127.0.0.1:5000/1
This is 5001
$ curl -H 'Host: example.com' http://127.0.0.1:5000/2
This is 5002
$ curl http://127.0.0.1:5000/1
curl: (52) Empty reply from server
$ curl http://127.0.0.1:5000/2
curl: (52) Empty reply from server
```

### CODE REVIEW

File: imports.go [hunk 1]
```diff
@@ -20,7 +20,9 @@ import (
 	_ "github.com/mholt/caddy-l4/modules/l4echo"
 	_ "github.com/mholt/caddy-l4/modules/l4http"
 	_ "github.com/mholt/caddy-l4/modules/l4proxy"
+	_ "github.com/mholt/caddy-l4/modules/l4proxyprotocol"
```
Comment (francislavoie) [inline imports.go:23]: Oh, was this just not working cause this was missing? Huh.

**Review by francislavoie — APPROVED** [review]
LGTM

File: imports.go (hunk 1 above)
Comment (RussellLuo) [reply imports.go:23]: Yeah, definitely! I just have no idea why it was OK when I tested it in #43 🤔

Comment (francislavoie) [reply imports.go:23]: Well, oops 😅

Comment (RussellLuo) [reply imports.go:23]: Oh, I got it! Because it has been imported by l4proxy:

https://github.com/mholt/caddy-l4/blob/d1f4337132468dfe2d081baba3769dfd1f46fbf8/modules/l4proxy/proxy.go#L31

**Review by mholt — APPROVED** [review]
Awesome, thanks for contributing this feature!
